apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
  labels:
    app: apache-server
spec:
  containers:
    - name: apache-container
      image: roxsross12/k8s_test_web:latest
      ports:
        - containerPort: 80