---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8sonfire-cluster
  region: us-east-1

iam:
  withOIDC: true

addons:
- name: vpc-cni 
  attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
- name: coredns
  version: latest 
- name: kube-proxy
  version: latest

managedNodeGroups:
- name: securityNodes
  minSize: 5
  maxSize: 10
  volumeSize: 30
  instanceType: t3.medium
  amiFamily: AmazonLinux2
  labels: { role: workers }
  tags:
    nodegroup-role: worker
  ssh:
    allow: true
    publicKeyName: guru

cloudWatch:
 clusterLogging:
   enableTypes: ["*"]